# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=10)),
                ('attempt', models.FloatField(verbose_name=100)),
                ('completion', models.FloatField(verbose_name=100)),
                ('att_pct', models.FloatField(verbose_name=100)),
            ],
        ),
    ]
