# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 20:35
from __future__ import unicode_literals

from django.db import migrations

from quarterback.models import Item
def add_data(apps, schema_editor):
    Item.objects.create(full_name="Cam Newton", team_name="CAR", attempt=53,completion=91, att_pct=58)
    Item.objects.create(full_name="Tom Brady", team_name="NE", attempt=55, completion=98, att_pct=56)
    Item.objects.create(full_name="Carson Palmer", team_name="ARI", attempt=48, completion=81, att_pct=59)
    Item.objects.create(full_name="Ben Roethlisberger", team_name="PIT", attempt=42, completion=68, att_pct=63)
    Item.objects.create(full_name="Peyton Manning", team_name="DEN", attempt=51, completion=92, att_pct=55)
    Item.objects.create(full_name="Russell Wilson", team_name="SEA", attempt=44, completion=74, att_pct=60)
    Item.objects.create(full_name="Aaron Rodgers", team_name="GB", attempt=45, completion=80, att_pct=56)
    Item.objects.create(full_name="Alex Smith", team_name="KC", attempt=46, completion=72, att_pct=64)
    Item.objects.create(full_name="Kirk Cousins", team_name="WAS", attempt=29, completion=46, att_pct=63)





class Migration(migrations.Migration):

    dependencies = [
        ('quarterback', '0001_initial'),
    ]

    operations = [
    ]
