# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarterback', '0002_auto_20160606_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='att_pct',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='attempt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='completion',
            field=models.FloatField(),
        ),
    ]
